# Generated by Django 5.2 on 2025-04-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('reading', 'Reading'), ('finished', 'Finished'), ('abandoned', 'Abandoned')], default='not_started', max_length=20)),
                ('review', models.TextField(blank=True)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
    ]
