# Generated by Django 5.1.7 on 2025-04-13 09:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_completed_book_progress_book_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='book',
            name='progress',
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Rating must be between 0 and 5', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='book',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ReadingChallenge',
        ),
    ]
