# Generated by Django 5.1.7 on 2025-05-15 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
