# Generated by Django 5.1.7 on 2025-05-19 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_goal_bookgoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
