# Generated by Django 5.1.7 on 2025-05-20 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_profile_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_verified',
        ),
    ]
