# Generated by Django 5.1.7 on 2025-05-22 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_alter_book_options_book_pages_read_book_total_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pages_read',
        ),
        migrations.CreateModel(
            name='ReadingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pages_read', models.PositiveIntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='books.book')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
